### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by palagyireka** [davidkrantz/FacebookChatStatistics#8]
Hi!
I am way too lame for your code, but I tried my best to install all the requirements, still when I try to run the program it gives me an error:
Traceback (most recent call last):
  File "C:\location\facebook_chat_statistics.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Can you help me with this?

**Comment by palagyireka** [comment]
UPDATE
Now after a few attempts it's giving me another error:
Traceback (most recent call last):
  File "C:\Users\user\Documents\Messenger\FacebookChatStatistics-master\facebook_chat_statistics.py", line 9, in <module>
    from facebook_messenger_conversation import FacebookMessengerConversation
  File "C:\Users\user\Documents\Messenger\FacebookChatStatistics-master\facebook_messenger_conversation.py", line 9, in <module>
    import emoji
ModuleNotFoundError: No module named 'emoji'

**Comment by davidkrantz** [comment]
Hello, it seems like the module "emoji" is not installed properly. Try installing it by running:
```
pip install emoji --upgrade
```
You might find more helpful information [here](https://pypi.org/project/emoji/).

**Comment by davidkrantz** [comment]
Hi @palagyireka! Have you gotten it to run? Can I close this issue?

**Comment by davidkrantz** [comment]
Closed due to inactivity.
