### ISSUE TITLE
Plots not working

### ISSUE THREAD

**Issue by augustin-smf** [davidkrantz/FacebookChatStatistics#9]
Hi,

First thank for this amazing idea and program, it's super fun.

I'm having a issue on generating de plots/charts.

and have the following error appearing 

> =================================== Averages ===================================
Average length of messages: 8.0 words
Average messages per day: 13.8
==================================== Plots =====================================
Traceback (most recent call last):
  File "/Users/aug/FacebookChatStatistics/facebook_chat_statistics.py", line 198, in <module>
    main()
  File "/Users/aug/FacebookChatStatistics/facebook_chat_statistics.py", line 57, in main
    names += '{}_{}_'.format(name[0], name[1])
IndexError: list index out of range

I'm running on MacOS (Silicon), python version is 3.9

If you have any idea.
Thanks

**Comment by davidkrantz** [comment]
Hello!

Are you getting those errors from a chat with a single person or is it a group chat?

Also, the code recently got updated, so please try again with the updated version of the code and see if the issue remains.
